### ISSUE TITLE
ImportError: cannot import name 'owlqn' 

### ISSUE THREAD

**Issue by Bmatist** [dedupeio/pylbfgs#14]
Hello,

I successfully installed PyLBFGS module and i can import it without errors, but the problem is when i want to import 'owlqn' with: "from pylbfgs import owlqn", it doesn't work.
I tested it on both windows and ubuntu and the same issue occures on both.
Can you please help.
Thanks in advance.
![Error](https://user-images.githubusercontent.com/50958849/58475088-487b0f00-814d-11e9-813f-ca2e70f7626f.PNG)

**Comment by maqifrnswa** [comment]
A bit late, but I think you are using a different pylbfgs. There's a different project also called pylbfgs that uses calls like you showed:
https://bitbucket.org/rtaylor/pylbfgs/src/master/

This project follows the same style as the original c library (you don't import owlqn)
