### ISSUE TITLE
Unable to install  getting error

### ISSUE THREAD

**Issue by iamMohamed** [dedupeio/pylbfgs#38]
Environment:
image: python:3.9.13-alpine3.15

Collecting pylbfgs==0.2.0.13 (from -r /tmp/tmpnqe55yh1 (line 173))
111.3   Downloading PyLBFGS-0.2.0.13.tar.gz (105 kB)
111.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.2/105.2 kB 4.8 MB/s eta 0:00:00
111.4   Installing build dependencies: started
120.7   Installing build dependencies: finished with status 'done'
120.7   Getting requirements to build wheel: started
121.4   Getting requirements to build wheel: finished with status 'error'
121.5   error: subprocess-exited-with-error
121.5   
121.5   × Getting requirements to build wheel did not run successfully.
121.5   │ exit code: 1
121.5   ╰─> [53 lines of output]
121.5       Compiling lbfgs/_lowlevel.pyx because it changed.
121.5       [1/1] Cythonizing lbfgs/_lowlevel.pyx
121.5       /tmp/pip-build-env-4zuuu0hm/overlay/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-c3shc_f2/pylbfgs_5d43d814162f405a9fc40586d659ea84/lbfgs/_lowlevel.pyx
121.5         tree = Parsing.p_module(s, pxd, full_module_name)
121.5       
121.5       Error compiling Cython file:
121.5       ------------------------------------------------------------
121.5       ...
121.5       
121.5               x_a = aligned_copy(x0.ravel())
121.5       
121.5               try:
121.5                   callback_data = (f, progress, x0.shape, args)
121.5                   r = lbfgs(n, x_a, fx_final, call_eval,
121.5                                               ^
121.5       ------------------------------------------------------------
121.5       
121.5       lbfgs/_lowlevel.pyx:395:40: Cannot assign type 'lbfgsfloatval_t (void *, lbfgsconst_p, lbfgsfloatval_t *, int, lbfgsfloatval_t) except? -1' to 'lbfgs_evaluate_t'
121.5       
121.5       Error compiling Cython file:
121.5       ------------------------------------------------------------
121.5       ...
121.5               x_a = aligned_copy(x0.ravel())
121.5       
121.5               try:
121.5                   callback_data = (f, progress, x0.shape, args)
121.5                   r = lbfgs(n, x_a, fx_final, call_eval,
121.5                             call_progress, <void *>callback_data, &self.params)
121.5                             ^
121.5       ------------------------------------------------------------
121.5       
121.5       lbfgs/_lowlevel.pyx:396:22: Cannot assign type 'int (void *, lbfgsconst_p, lbfgsconst_p, lbfgsfloatval_t, lbfgsfloatval_t, lbfgsfloatval_t, lbfgsfloatval_t, int, int, int) except? -1' to 'lbfgs_progress_t'
121.5       Traceback (most recent call last):
121.5         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
121.5           main()
121.5         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
121.5           json_out['return_val'] = hook(**hook_input['kwargs'])
121.5         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
121.5           return hook(config_settings)
121.5         File "/tmp/pip-build-env-4zuuu0hm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
121.5           return self._get_build_requires(config_settings, requirements=['wheel'])
121.5         File "/tmp/pip-build-env-4zuuu0hm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
121.5           self.run_setup()
121.5         File "/tmp/pip-build-env-4zuuu0hm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
121.5           super(_BuildMetaLegacyBackend,
121.5         File "/tmp/pip-build-env-4zuuu0hm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
121.5           exec(code, locals())
121.5         File "<string>", line 27, in <module>
121.5         File "/tmp/pip-build-env-4zuuu0hm/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
121.5           cythonize_one(*args)
121.5         File "/tmp/pip-build-env-4zuuu0hm/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
121.5           raise CompileError(None, pyx_file)
121.5       Cython.Compiler.Errors.CompileError: lbfgs/_lowlevel.pyx
121.5       [end of output]
121.5   
121.5   note: This error originates from a subprocess, and is likely not a problem with pip.
121.5 error: subprocess-exited-with-error
121.5 
121.5 × Getting requirements to build wheel did not run successfully.
121.5 │ exit code: 1
121.5 ╰─> See above for output.
121.5 
121.5 note: This error originates from a subprocess, and is likely not a problem with pip.
122.2 Traceback (most recent call last):
122.2   File "/usr/local/bin/pip-sync", line 8, in <module>
122.2     sys.exit(cli())
122.2   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
122.2     return self.main(*args, **kwargs)
122.2   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
122.2     rv = self.invoke(ctx)
122.2   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
122.2     return ctx.invoke(self.callback, **ctx.params)
122.2   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
122.2     return __callback(*args, **kwargs)
122.2   File "/usr/local/lib/python3.9/site-packages/piptools/scripts/sync.py", line 203, in cli
122.2     sync.sync(
122.2   File "/usr/local/lib/python3.9/site-packages/piptools/sync.py", line 263, in sync
122.2     run(  # nosec
122.2   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
122.2     raise CalledProcessError(retcode, process.args,
122.2 subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', '-r', '/tmp/tmpnqe55yh1']' returned non-zero exit status 1.

**Comment by fzimmermann89** [comment]
First guess would be a cython 3 incompatibility?
Maybe as a hotfix we can limit the build dependency to a version earlier than 3.0.

**Comment by iamMohamed** [comment]
Hello @fzimmermann89 

Thanks for your reply, I really appreciate it, I am new to docker, Could you guide me to do it?

**Comment by fzimmermann89** [comment]
For now, you may use 
`pip install git+https://github.com/fzimmermann89/pylbfgs.git@fzimmermann89-cython` to install a fixed version

**Comment by da-woods** [comment]
So just to clarify: the source of the issue in Cython 3.0 isn't compatible because we've changed the default behaviour of cdef functions to be able to propagate exceptions. This means that you can't assign them to a function point where the function pointer expects a function that won't propagate exceptions.

This is an incompatible change, but by design. We're going to improve the error message a little in the next release I think to give a bit more guidance about how to fix it.

The solution is likely to add noexcept to functions that are used as pointers.

**Comment by iamMohamed** [comment]
Thanks @da-woods

**Comment by iamMohamed** [comment]
Any update on this one we are unable to deploy our app due to this

**Comment by iamMohamed** [comment]
Hello @fzimmermann89 

I need to build a Django docker image, in my requirement file this module is dependent Since I am unable to install this, I can't build a docker image can you suggest me anything?

**Comment by fzimmermann89** [comment]
So you have a requirements.txt that specifies this package?

And this requirements.txt you use in a docker file?

If yes, either do the pip install mentioned above before installing the requirements.txt contents,
or specify  the dependency in the requirements.txt as: 
pylbfgs @ git+https://github.com/fzimmermann89/pylbfgs.git@fzimmermann89-cython 
to install a fixed version.

**Comment by iamMohamed** [comment]
Hello @fzimmermann89 

Thanks working.
