### ISSUE TITLE
Not compatible with python 3.11

### ISSUE THREAD

**Issue by jack-odonoghue** [dedupeio/pylbfgs#40]

**Comment by sbrenner1982** [comment]
<pre>Collecting pylbfgs
  Using cached PyLBFGS-0.2.0.14.tar.gz (98 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  <font color="#C01C28"><b>error</b></font>: <b>subprocess-exited-with-error</b>
  
  <font color="#C01C28">×</font> <font color="#26A269">Getting requirements to build wheel</font> did not run successfully.
  <font color="#C01C28">│</font> exit code: <font color="#2AA1B3"><b>1</b></font>
  <font color="#C01C28">╰─&gt;</font> <font color="#C01C28">[56 lines of output]</font>
  <font color="#C01C28">   </font> /tmp/pip-build-env-2g2k_p17/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive &apos;language_level&apos; not set, using &apos;3str&apos; for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-1_i61yy0/pylbfgs_7a13b0d8215f41f8952b32da42f79255/lbfgs/_lowlevel.pyx</pre>

**Comment by BernhardSchlegel** [comment]
Any updates on this?
